export interface Voucher {
  voucher_id: number,
  bu_id: number,
  campaigntype_id: number,
  voucher_code: string,
  voucher_name: string,
  voucher_description: string,
  toc: string,
  region: string,
  valid_start: string,
  valid_end: string,
  start_until: string,
  end_at: string,
  minimun_use: number,
  maximum_use: number,
  user_registration_type: number,
  kuota: number,
  status: string,
  deleted_at: string | null,
  created_at: string,
  updated_at: string,
}
