stages:
    - build-migrate
    - migrate
    - build-container
    - deploy

docker-build-prod:
  stage: build-container
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 261622543538.dkr.ecr.ap-southeast-1.amazonaws.com
  script:
    - echo "Disini Build Docker"
    - docker build -t voucher-global-web-zeus .
    - docker tag voucher-global-web-zeus:latest 261622543538.dkr.ecr.ap-southeast-1.amazonaws.com/voucher-global-web-zeus:prod
    - docker push 261622543538.dkr.ecr.ap-southeast-1.amazonaws.com/voucher-global-web-zeus:prod
    - echo "Build successfully!"
  only:
    - prod

docker-build-dev:
  stage: build-container
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 261622543538.dkr.ecr.ap-southeast-1.amazonaws.com
  script:
    - echo "Disini Build Docker"
    - docker build -t voucher-global-web-zeus .
    - docker tag voucher-global-web-zeus:latest 261622543538.dkr.ecr.ap-southeast-1.amazonaws.com/voucher-global-web-zeus:dev
    - docker push 261622543538.dkr.ecr.ap-southeast-1.amazonaws.com/voucher-global-web-zeus:dev
    - echo "Build successfully!"
  only:
    - dev

deploy-to-ECS-dev:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
  script:
    - echo "mulai deploy ke server"
    - ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST_DEV "aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 261622543538.dkr.ecr.ap-southeast-1.amazonaws.com"
    - ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST_DEV "cp ~/../ubuntu/Projects/env/voucher-global-web-zeus.env .env"
    - ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST_DEV "docker pull 261622543538.dkr.ecr.ap-southeast-1.amazonaws.com/voucher-global-web-zeus:dev"
    - ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST_DEV "docker stop voucher-global-web-zeus || true && docker rm voucher-global-web-zeus || true"
    - ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST_DEV "docker run -d --network host --restart unless-stopped --name voucher-global-web-zeus --env-file ./.env 261622543538.dkr.ecr.ap-southeast-1.amazonaws.com/voucher-global-web-zeus:dev"
    - ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST_DEV "docker image prune -a -f"
  only:
    - dev

deploy-to-ECS-prod:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
  script:
    - echo "mulai deploy ke server"
    - ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 261622543538.dkr.ecr.ap-southeast-1.amazonaws.com"
    - ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "cp ~/../ubuntu/Projects/env/voucher-global-web-zeus.env .env"
    - ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "docker pull 261622543538.dkr.ecr.ap-southeast-1.amazonaws.com/voucher-global-web-zeus:prod"
    - ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "docker stop voucher-global-web-zeus || true && docker rm voucher-global-web-zeus || true"
    - ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "docker run -d --network host --restart unless-stopped --name voucher-global-web-zeus --env-file ./.env 261622543538.dkr.ecr.ap-southeast-1.amazonaws.com/voucher-global-web-zeus:prod"
    - ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "docker image prune -a -f"
  only:
    - prod
