export const PATH_NAME = {
  ROOT: '/',
  ERROR_404: '/404',
  ERROR_403: '/403',
  DASHBOARD: '/dashboard',
  PLAY_BACKGROUND: '/playbackground',
  LOGIN: '/login',
  PRODUCT: '/product',
  PRODUCT_LIST: '/product/list',
  PRODUCT_ADD: '/product/add',
  USERS: '/users',
  KANBAN: '/kanban',
  BISNISUNIT_LIST: '/bisnisunit/list',
  BISNISUNIT_ADD: '/bisnisunit/add',
  MASTER_LIST: '/master/list',
  MASTER_ADD: '/master/add',
  CONDITION_LIST: '/condition/list',
  CONDITION_ADD: '/condition/add',
  VOUCHER_LIST: '/voucher/list',
  VOUCHER_ADD: '/voucher/add',
};
